/*  =========================================================================
    libzsync - LIBZSYNC wrapper

    Copyright (c) the Contributors as noted in the AUTHORS file.         
    This file is part of libzsync, the peer to peer file sharing library:
    http://zerosync.org.                                                 
                                                                         
    This Source Code Form is subject to the terms of the Mozilla Public  
    License, v. 2.0. If a copy of the MPL was not distributed with this  
    file, You can obtain one at http://mozilla.org/MPL/2.0/.             

################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
    =========================================================================
*/

#ifndef libzsync_library_H_INCLUDED
#define libzsync_library_H_INCLUDED

//  Set up environment for the application

//  External dependencies
#include <zyre.h>

//  LIBZSYNC version macros for compile-time API detection

#define LIBZSYNC_VERSION_MAJOR 1
#define LIBZSYNC_VERSION_MINOR 0
#define LIBZSYNC_VERSION_PATCH 0

#define LIBZSYNC_MAKE_VERSION(major, minor, patch) \
    ((major) * 10000 + (minor) * 100 + (patch))
#define LIBZSYNC_VERSION \
    LIBZSYNC_MAKE_VERSION(LIBZSYNC_VERSION_MAJOR, LIBZSYNC_VERSION_MINOR, LIBZSYNC_VERSION_PATCH)

#if defined (__WINDOWS__)
#   if defined LIBLIBZSYNC_STATIC
#       define LIBZSYNC_EXPORT
#   elif defined LIBLIBZSYNC_EXPORTS
#       define LIBZSYNC_EXPORT __declspec(dllexport)
#   else
#       define LIBZSYNC_EXPORT __declspec(dllimport)
#   endif
#else
#   define LIBZSYNC_EXPORT
#endif

//  Opaque class structures to allow forward references
typedef struct _zsync_t zsync_t;
#define ZSYNC_T_DEFINED


//  Public API classes
#include "zsync.h"

#endif
/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
*/
