/*  =========================================================================
    libzsync_classes - private header file

    Copyright (c) the Contributors as noted in the AUTHORS file.         
    This file is part of libzsync, the peer to peer file sharing library:
    http://zerosync.org.                                                 
                                                                         
    This Source Code Form is subject to the terms of the Mozilla Public  
    License, v. 2.0. If a copy of the MPL was not distributed with this  
    file, You can obtain one at http://mozilla.org/MPL/2.0/.             
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
    =========================================================================
*/

#ifndef LIBZSYNC_CLASSES_H_INCLUDED
#define LIBZSYNC_CLASSES_H_INCLUDED

//  External API
#include "../include/libzsync.h"

//  Internal API
#include "zsync_node.h"
#include "zsync_peer.h"
#include "zsync_inbox.h"
#include "zsync_outbox.h"

#include "zsync_msg.h"

#endif
